fix(log,cache): anonymous and hashed queries
hearchco/agent pull request #181
Opened 2024-01-14 02:23 UTC by aleksasiriski

2024-01-19 14:27 UTC, hiddenMedic requested changes

2024-01-19 14:27 UTC, k4lizen commented on src/anonymize/string.go
> +	rand.New(rand.NewSource(time.Now().Unix()))
`Shuffle()` should probably be called on the object returned from `rand.New()` ?

2024-01-19 14:27 UTC, k4lizen commented on src/anonymize/string.go
> +		}
Could just be:
```go
if !encountered[char]{
    encountered[char] = true
    dedupStr += string(char)
}
```
no?

2024-01-19 18:56 UTC, aleksasiriski commented on src/anonymize/string.go
> +	rand.New(rand.NewSource(time.Now().Unix()))
Yes, good catch! Thanks!

2024-02-07 23:47 UTC, hiddenMedic approved these changes

2024-02-07 23:49 UTC, merged