Image bing rev
hearchco/agent pull request #223
Opened 2024-02-23 01:52 UTC by k4lizen

2024-02-23 08:53 UTC, aleksasiriski commented on src/search/engines/bingimages/bingimages.go
> +			// could also use the json data ("t" field)
Any reason not to use it? If it's always there it will make colly do less which is good

2024-02-23 08:56 UTC, aleksasiriski requested changes
Unit tests must work

2024-02-23 08:56 UTC, aleksasiriski commented on src/search/engines/bingimages/dom.go
> +	Result: "ul.dgControl_list > li[data-idx] > div.iuscp:not([data-evt])",
This breaks `make test-engines` bingimages. Reverting it seems to prove that everything else in this PR is good except this.

2024-02-23 17:15 UTC, k4lizen commented on src/search/engines/bingimages/bingimages.go
> +			// could also use the json data ("t" field)
I simply don't know if its always there. 
I'll change it to use the json field.
If we notice that the json field can be missing (i.e. it errors out), we will add the html field as a callback (its better to keep it simple now if it works).

2024-02-24 09:37 UTC, aleksasiriski approved these changes
LGTM

2024-02-24 09:47 UTC, merged